name: Open World Core Release
on:
  workflow_dispatch:
    inputs:
      confirmation:
        description: 'confirmation to release on maven central'
        required: true
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "JDK set-up"
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - run: mvn verify
  deploy:
    needs: test
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.release_artifact.outputs.version }}
    steps:
      - uses: actions/checkout@v3
      - name: "JDK set-up"
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: "Release artifacts"
        id: release_artifact
        run: |
          current_version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "::set-output name=version::${current_version}"
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git tag -a "$current_version" -m "Release $current_version"
          git push origin --tags
  update-bom:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Update BOM
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://api.github.com/repos/Hamzanael/openworld-sdk-java/actions/workflows/update-bom-version-actions.yml/dispatches'
          method: 'POST'
          customHeaders: '{"Authorization": "${{secrets.CUSTOM_TOKEN}}","Accept": "application/vnd.github+json"}'
          data: '{"ref":"main","inputs":{"sdk-version":"${{needs.deploy.outputs.version}}","sdk-name":"openworld-java-sdk-core"}}'
